name: C/C++ CI

on:
  push:
    branches: [ "pon_rt" ]
  pull_request:
    branches: [ "pon_rt" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make re
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
